package services

















































































































































}	}		})			"details": err.Error(),			"error":   "Failed to calculate sell routes",		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{		// Generic error (ESI timeout, database error, etc.)	default:		})			"details": err.Error(),			"error":   "Invalid location",		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{	case errors.Is(err, services.ErrInvalidLocation):		})			"details": err.Error(),			"error":   "Failed to determine starting system",		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{	case errors.Is(err, services.ErrLocationNotFound):		})			"error": "Character must be docked at a station to calculate sell routes",		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{	case errors.Is(err, services.ErrNotDocked):	switch {func handleBusinessError(c *fiber.Ctx, err error) error {// Centralizes error handling logic// handleBusinessError maps business errors to appropriate HTTP responses// ============================================================================// Error Handling// ============================================================================}	return c.JSON(result)	}		return c.Status(fiber.StatusPartialContent).JSON(result)		c.Set("Warning", `199 - "`+result.Warning+`"`)	if result.Warning != "" {	// Check for timeout warning (partial results)	}		})			"details": err.Error(),			"error":   "Failed to calculate routes",		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{	if err != nil {	result, err := h.routeCalculator.Calculate(c.Context(), req.RegionID, req.ShipTypeID, req.CargoCapacity)	// Calculate routes	}		})			"error": err.Error(),		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{	if err := req.Validate(); err != nil {	// Validate request	}		})			"error": "Invalid request body",		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{	if err := c.BodyParser(&req); err != nil {	var req models.RouteCalculationRequest	// Parse requestfunc (h *TradingHandler) CalculateRoutes(c *fiber.Ctx) error {// CalculateRoutes handles POST /api/v1/trading/routes/calculate}	})		"count":  len(routes),		"routes": routes,	return c.JSON(fiber.Map{	// 5. Return Success Response	}		return handleBusinessError(c, err)	if err != nil {	)		accessToken,		characterID,		req,		c.Context(),	routes, err := h.inventorySellOrchestrator.CalculateSellRoutes(	// 4. Delegate to Orchestrator (single call replaces 5+ service calls)	accessToken := c.Locals("access_token").(string)	characterID := c.Locals("character_id").(int)	// 3. Extract Auth Context (set by auth middleware)	}		})			"error": err.Error(),		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{	if err := req.Validate(); err != nil {	// 2. Validate Request (delegated to model)	}		})			"error": "Invalid request body",		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{	if err := c.BodyParser(&req); err != nil {	var req models.InventorySellRequest	// 1. Parse Request Bodyfunc (h *TradingHandler) CalculateInventorySellRoutes(c *fiber.Ctx) error {// REFACTORED: Reduced from 80 lines to 25 lines by delegating to orchestrator// CalculateInventorySellRoutes handles POST /api/v1/trading/inventory-sell}	}		routeCalculator:           routeCalc,		inventorySellOrchestrator: inventorySellOrch,	return &TradingHandler{) *TradingHandler {	routeCalc services.RouteCalculationService,	inventorySellOrch services.InventorySellOrchestrator,func NewTradingHandler(// NewTradingHandler creates a new trading handler instance}	routeCalculator services.RouteCalculationService	// Direct services (single-step operations)	inventorySellOrchestrator services.InventorySellOrchestrator	// Facade services (orchestrate multi-step workflows)type TradingHandler struct {// Does NOT contain business logic (delegated to services)// - Error code translation// - HTTP response mapping// - Request parsing & validation// Responsibilities:// TradingHandler handles HTTP requests for trading operations)	"github.com/gofiber/fiber/v2"	"github.com/Sternrassler/eve-o-provit/backend/internal/services"	"github.com/Sternrassler/eve-o-provit/backend/internal/models"	"errors"import (package handlers// File: internal/handlers/trading.go (REFACTORED VERSION)// Package handlers - Refactored Trading Handler (Thin Handler Pattern)