package services







































































































}	return fmt.Errorf("invalid %s: '%s' (must be one of: %v)", fieldName, value, validValues)	}		}			return nil		if value == valid {	for _, valid := range validValues {func ValidateEnum(value string, validValues []string, fieldName string) error {// ValidateEnum checks if a string is in a set of valid values}	return nil	}		return fmt.Errorf("invalid %s: %.2f (must be positive)", fieldName, value)	if value <= 0 {func ValidatePositiveFloat(value float64, fieldName string) error {// ValidatePositiveFloat checks if a float is positive}	return nil	}		return fmt.Errorf("invalid %s: %d (must be positive)", fieldName, value)	if value <= 0 {func ValidatePositiveInt(value int, fieldName string) error {// ValidatePositiveInt checks if an integer is positive// ============================================================================// General Validation Helpers// ============================================================================}	return nil	}		return fmt.Errorf("invalid cargo_capacity: %.2f (must be non-negative)", r.CargoCapacity)	if r.CargoCapacity < 0 {	// Cargo capacity validation (optional, but if provided must be positive)	}		return fmt.Errorf("invalid ship_type_id: %d (must be positive)", r.ShipTypeID)	if r.ShipTypeID <= 0 {	// Ship type ID validation	}		return fmt.Errorf("invalid region_id: %d (must be positive)", r.RegionID)	if r.RegionID <= 0 {	// Region ID validationfunc (r *RouteCalculationRequest) Validate() error {// Validate validates the route calculation request// ============================================================================// RouteCalculationRequest Validation// ============================================================================}	return nil	}		return errors.New("invalid security_filter: must be one of: all, highsec, highlow")	if !validFilters[r.SecurityFilter] {	}		"highlow": true, // Exclude nullsec (>0.0)		"highsec": true, // Only >= 0.5 security		"all":     true, // Explicit all systems		"":        true, // Empty = all systems	validFilters := map[string]bool{	// Security filter validation	}		return errors.New("invalid region_id: must be positive")	if r.RegionID <= 0 {	// Region ID validation	}		return errors.New("invalid buy_price_per_unit: must be positive")	if r.BuyPricePerUnit <= 0 {	// Buy price validation	}		return errors.New("invalid quantity: must be positive")	if r.Quantity <= 0 {	// Quantity validation	}		return errors.New("invalid type_id: must be positive")	if r.TypeID <= 0 {	// Type ID validationfunc (r *InventorySellRequest) Validate() error {// Extracted from handler to make validation reusable and testable// Validate validates the inventory sell request// ============================================================================// InventorySellRequest Validation// ============================================================================)	"fmt"	"errors"import (package models// File: internal/models/validation.go// Package models - Request Validation (Extracted from Handler)