// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "EVE-O-Provit Team",
            "url": "https://github.com/Sternrassler/eve-o-provit",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/character": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get authenticated character information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Get character info",
                "responses": {
                    "200": {
                        "description": "Character info with character_id, character_name, scopes, portrait_url",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/character/location": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get character's current location (solar system)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Get character location",
                "responses": {
                    "200": {
                        "description": "Location data with solar_system_id, station_id, structure_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/character/ship": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get character's current active ship",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Get current ship",
                "responses": {
                    "200": {
                        "description": "Ship data with ship_item_id, ship_name, ship_type_id, ship_type_name",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/character/ships": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of all character's ships in current hangar",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Get character ships",
                "responses": {
                    "200": {
                        "description": "Array of ships with ship_item_id, ship_name, ship_type_id, ship_type_name",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/character/wallet": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the authenticated character's wallet balance in ISK (used to prefill ROI capital)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Get character wallet balance",
                "responses": {
                    "200": {
                        "description": "Object with balance (float, ISK)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/characters/{characterId}/fitting/{shipTypeId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve character's ship fitting with deterministic bonus calculations\nCalculates effective cargo capacity, warp speed with skills and modules\nUses EVE dogma engine with stacking penalties",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fitting"
                ],
                "summary": "Get character ship fitting",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 12345678,
                        "description": "Character ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 650,
                        "description": "Ship Type ID",
                        "name": "shipTypeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Force cache refresh",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CharacterFittingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/characters/{characterId}/skills": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve character skills from ESI with Redis caching\nGraceful degradation: Returns default skills (level 0) if ESI fails",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Get character skills",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 12345678,
                        "description": "Character ID",
                        "name": "characterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CharacterSkillsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/esi/ui/autopilot/waypoint": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Set autopilot waypoint in EVE client via ESI UI API\nRequires scope: esi-ui.write_waypoint.v1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ESI UI"
                ],
                "summary": "Set autopilot waypoint",
                "parameters": [
                    {
                        "description": "Waypoint request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "add_to_beginning": {
                                    "type": "boolean"
                                },
                                "clear_other_waypoints": {
                                    "type": "boolean"
                                },
                                "destination_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Waypoint set successfully"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/esi/ui/openwindow/marketdetails": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Opens the market window for a given type_id in the EVE client.\nRequires scope: esi-ui.open_window.v1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ESI UI"
                ],
                "summary": "Open market details window in EVE client",
                "parameters": [
                    {
                        "description": "Type ID to open",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "type_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Market details window opened"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Check API and database health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/items/search": {
            "get": {
                "description": "Search for EVE Online items by name (fuzzy matching)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "Search EVE items",
                "parameters": [
                    {
                        "minLength": 3,
                        "type": "string",
                        "description": "Search query (min 3 characters)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum results (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ItemSearchResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/market/staleness/{region}": {
            "get": {
                "description": "Check how old the cached market data is for a region\nStatus: fresh (\u003c30min), stale (30-60min), very_stale (\u003e60min)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market"
                ],
                "summary": "Get market data staleness",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 10000002,
                        "description": "Region ID",
                        "name": "region",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/MarketDataStalenessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/market/{region}/{type}": {
            "get": {
                "description": "Retrieve market orders for a specific item type in a region\nSupports optional refresh from ESI (cached for 5 minutes)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market"
                ],
                "summary": "Get market orders",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 10000002,
                        "description": "Region ID",
                        "name": "region",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 34,
                        "description": "Type ID",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Force refresh from ESI",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/MarketOrderResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/mining/ore-ranking": {
            "post": {
                "description": "Given a region (or the character's current region) and a security band,\nranks ores by net ISK per m³ and — when a mining ship is fitted — per hour,\ncomparing selling the raw ore vs reprocessing + selling the materials.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mining"
                ],
                "summary": "Rank asteroid ores by raw-vs-refine net ISK for a region + security band",
                "parameters": [
                    {
                        "description": "Ore ranking parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OreRankingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OreRankingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sde/regions": {
            "get": {
                "description": "Get list of all EVE Online regions from SDE",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDE"
                ],
                "summary": "List all EVE regions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/RegionResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trading/assets": {
            "get": {
                "description": "Returns the character's assets aggregated by (type, location) with quantity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "List owned items aggregated by type and location",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AssetsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trading/assets/sell-options": {
            "post": {
                "description": "For a selected owned item, ranks instant-sell (taker) locations across the\nmajor hubs + the item's current region by net proceeds, with route info.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "Rank taker sell locations for one owned item",
                "parameters": [
                    {
                        "description": "Selected item",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SellOptionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SellOptionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trading/hauling/routes": {
            "post": {
                "description": "From the character's current region + adjacent regions, finds cross-region\narbitrage routes with an optimal per-trip cargo load (cargo + capital).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "Find profitable station→station hauling routes in the neighborhood",
                "parameters": [
                    {
                        "description": "Hauling parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/HaulingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HaulingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trading/hubs/compare": {
            "post": {
                "description": "For a given item, compares buy/sell/spread, skill-adjusted net margin,\nvolume and competition across Jita, Amarr, Dodixie, Rens, Hek.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "Compare an item's station-trading profitability across major hubs",
                "parameters": [
                    {
                        "description": "Item to compare",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/HubComparisonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HubComparisonResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trading/portfolio/optimize": {
            "post": {
                "description": "Given region, ship, capital and time budget, suggests how to allocate\ncapital across items (greedy, under liquidity + per-item caps).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "Optimize capital allocation across items for max daily profit",
                "parameters": [
                    {
                        "description": "Optimization parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PortfolioRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PortfolioResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/trading/routes/calculate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Calculate optimal intra-region trading routes with profit analysis\nUses character skills and ship fitting for accurate cargo capacity\nSupports deterministic navigation parameters (warp_speed, align_time) from frontend fitting calculation\nSupports volume filtering for liquidity-based selection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trading"
                ],
                "summary": "Calculate trading routes",
                "parameters": [
                    {
                        "description": "Route calculation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RouteCalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully calculated routes",
                        "schema": {
                            "$ref": "#/definitions/models.RouteCalculationResponse"
                        }
                    },
                    "206": {
                        "description": "Partial results (timeout)",
                        "schema": {
                            "$ref": "#/definitions/models.RouteCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/types/{id}": {
            "get": {
                "description": "Retrieve detailed information about an EVE Online item type from SDE",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SDE"
                ],
                "summary": "Get item type information",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TypeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/version": {
            "get": {
                "description": "Get API version information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "API version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VersionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CharacterFittingResponse": {
            "type": "object",
            "properties": {
                "align_time_seconds": {
                    "description": "Deterministic align time (with skills + modules)",
                    "type": "number",
                    "example": 4.82
                },
                "applied_skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Gallente Hauler V",
                        "Navigation V"
                    ]
                },
                "base_cargo_hold_m3": {
                    "type": "number",
                    "example": 2700
                },
                "base_fuel_bay_m3": {
                    "type": "number",
                    "example": 0
                },
                "base_warp_speed_au_s": {
                    "type": "number",
                    "example": 3
                },
                "cached_until": {
                    "type": "string",
                    "example": "2025-11-12T11:00:00Z"
                },
                "character_id": {
                    "type": "integer",
                    "example": 12345678
                },
                "effective_cargo_m3": {
                    "type": "number",
                    "example": 9656.9
                },
                "fitted_modules": {
                    "type": "integer",
                    "example": 5
                },
                "inertia_modifier": {
                    "type": "number",
                    "example": 1
                },
                "ship_name": {
                    "type": "string",
                    "example": "Nereus"
                },
                "ship_type_id": {
                    "type": "integer",
                    "example": 650
                },
                "warp_speed_au_s": {
                    "type": "number",
                    "example": 6.87
                }
            }
        },
        "CharacterSkill": {
            "type": "object",
            "properties": {
                "active_skill_level": {
                    "type": "integer",
                    "example": 5
                },
                "skill_id": {
                    "type": "integer",
                    "example": 3340
                },
                "skillpoints_in_skill": {
                    "type": "integer",
                    "example": 256000
                },
                "trained_skill_level": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "CharacterSkillsResponse": {
            "type": "object",
            "properties": {
                "cached_until": {
                    "type": "string",
                    "example": "2025-11-12T11:00:00Z"
                },
                "character_id": {
                    "type": "integer",
                    "example": 12345678
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/CharacterSkill"
                    }
                },
                "total_sp": {
                    "type": "integer",
                    "example": 50000000
                },
                "unallocated_sp": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "CompetitionInfo": {
            "type": "object",
            "properties": {
                "changes_per_hour": {
                    "type": "number",
                    "example": 42.5
                },
                "source": {
                    "description": "\"live\" | \"baseline\"",
                    "type": "string",
                    "example": "baseline"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                },
                "message": {
                    "type": "string",
                    "example": "Detailed error message"
                }
            }
        },
        "HaulingItem": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "profit": {
                    "description": "net profit for this position",
                    "type": "number"
                },
                "profit_per_m3": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "sell_price": {
                    "type": "number"
                },
                "type_id": {
                    "type": "integer"
                },
                "unit_volume": {
                    "type": "number"
                }
            }
        },
        "HaulingRequest": {
            "type": "object",
            "properties": {
                "avoid_low_sec": {
                    "type": "boolean"
                },
                "capital": {
                    "type": "number"
                },
                "cargo_capacity": {
                    "description": "Optional: selected ship instance's effective cargo (m³). When \u003e0, overrides the per-type recompute.",
                    "type": "number"
                },
                "max_routes": {
                    "description": "0 = default 15",
                    "type": "integer"
                },
                "origin_region_id": {
                    "description": "0 = use character's current region",
                    "type": "integer"
                },
                "ship_type_id": {
                    "type": "integer"
                }
            }
        },
        "HaulingResponse": {
            "type": "object",
            "properties": {
                "origin_region_id": {
                    "type": "integer"
                },
                "regions_scanned": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HaulingRoute"
                    }
                },
                "skills_applied": {
                    "$ref": "#/definitions/SkillsApplied"
                }
            }
        },
        "HaulingRoute": {
            "type": "object",
            "properties": {
                "buy_station_id": {
                    "type": "integer"
                },
                "buy_station_name": {
                    "type": "string"
                },
                "buy_system_name": {
                    "type": "string"
                },
                "isk_per_hour": {
                    "type": "number"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HaulingItem"
                    }
                },
                "jumps": {
                    "type": "integer"
                },
                "security_risk": {
                    "description": "\"safe\" | \"caution\" | \"danger\"",
                    "type": "string"
                },
                "sell_station_id": {
                    "type": "integer"
                },
                "sell_station_name": {
                    "type": "string"
                },
                "sell_system_name": {
                    "type": "string"
                },
                "total_capital": {
                    "type": "number"
                },
                "total_profit": {
                    "type": "number"
                },
                "total_volume": {
                    "type": "number"
                },
                "travel_time_min": {
                    "type": "number"
                }
            }
        },
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-11-12T10:00:00Z"
                }
            }
        },
        "HubComparisonRequest": {
            "type": "object",
            "properties": {
                "type_id": {
                    "type": "integer",
                    "example": 34
                }
            }
        },
        "HubComparisonResult": {
            "type": "object",
            "properties": {
                "best_hub_region_id": {
                    "type": "integer",
                    "example": 10000032
                },
                "hubs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HubRow"
                    }
                },
                "item_name": {
                    "type": "string",
                    "example": "Tritanium"
                },
                "skills_applied": {
                    "$ref": "#/definitions/SkillsApplied"
                },
                "type_id": {
                    "type": "integer",
                    "example": 34
                }
            }
        },
        "HubRow": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number",
                    "example": 5.5
                },
                "competition": {
                    "$ref": "#/definitions/CompetitionInfo"
                },
                "daily_volume": {
                    "type": "number",
                    "example": 125000
                },
                "has_data": {
                    "type": "boolean",
                    "example": true
                },
                "hub_name": {
                    "type": "string",
                    "example": "Jita"
                },
                "liquidity_score": {
                    "type": "integer",
                    "example": 72
                },
                "net_margin_percent": {
                    "type": "number",
                    "example": 3.4
                },
                "net_profit_per_unit": {
                    "type": "number",
                    "example": 0.18
                },
                "region_id": {
                    "type": "integer",
                    "example": 10000002
                },
                "region_name": {
                    "type": "string",
                    "example": "The Forge"
                },
                "sell_price": {
                    "type": "number",
                    "example": 6.1
                },
                "spread_percent": {
                    "type": "number",
                    "example": 10.9
                },
                "system_id": {
                    "type": "integer",
                    "example": 30000142
                },
                "tier": {
                    "description": "\"primary\" | \"secondary\"",
                    "type": "string",
                    "example": "primary"
                }
            }
        },
        "ItemSearchResult": {
            "type": "object",
            "properties": {
                "group_name": {
                    "type": "string",
                    "example": "Mineral"
                },
                "name": {
                    "type": "string",
                    "example": "Tritanium"
                },
                "type_id": {
                    "type": "integer",
                    "example": 34
                }
            }
        },
        "MarketDataStalenessResponse": {
            "type": "object",
            "properties": {
                "age_minutes": {
                    "type": "integer",
                    "example": 15
                },
                "last_update": {
                    "type": "string",
                    "example": "2025-11-12T10:00:00Z"
                },
                "refresh_allowed": {
                    "type": "boolean",
                    "example": true
                },
                "region_id": {
                    "type": "integer",
                    "example": 10000002
                },
                "region_name": {
                    "type": "string",
                    "example": "The Forge"
                },
                "status": {
                    "description": "fresh, stale, very_stale",
                    "type": "string",
                    "example": "fresh"
                }
            }
        },
        "MarketOrderResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer",
                    "example": 90
                },
                "is_buy_order": {
                    "type": "boolean",
                    "example": false
                },
                "issued": {
                    "type": "string",
                    "example": "2025-11-12T10:00:00Z"
                },
                "location_id": {
                    "type": "integer",
                    "example": 60003760
                },
                "min_volume": {
                    "type": "integer",
                    "example": 1
                },
                "order_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "price": {
                    "type": "number",
                    "example": 5.5
                },
                "range": {
                    "type": "string",
                    "example": "region"
                },
                "system_id": {
                    "type": "integer",
                    "example": 30000142
                },
                "type_id": {
                    "type": "integer",
                    "example": 34
                },
                "volume_remain": {
                    "type": "integer",
                    "example": 100000
                },
                "volume_total": {
                    "type": "integer",
                    "example": 100000
                }
            }
        },
        "PortfolioItem": {
            "type": "object",
            "properties": {
                "buy_station_id": {
                    "type": "integer"
                },
                "buy_station_name": {
                    "type": "string"
                },
                "buy_system_name": {
                    "description": "Where to execute the haul: buy at the buy station, sell at the sell station.",
                    "type": "string"
                },
                "capital_used": {
                    "type": "number"
                },
                "daily_profit": {
                    "type": "number"
                },
                "isk_per_hour": {
                    "description": "net daily profit per hour of haul time",
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "roi_percent": {
                    "description": "daily_profit / capital_used * 100",
                    "type": "number"
                },
                "sell_station_id": {
                    "type": "integer"
                },
                "sell_station_name": {
                    "type": "string"
                },
                "sell_system_name": {
                    "type": "string"
                },
                "trips_per_day": {
                    "type": "number"
                },
                "type_id": {
                    "type": "integer"
                },
                "units": {
                    "type": "integer"
                }
            }
        },
        "PortfolioRequest": {
            "type": "object",
            "properties": {
                "capital": {
                    "description": "ISK budget",
                    "type": "number"
                },
                "cargo_capacity": {
                    "description": "Optional: selected ship instance's effective cargo (m³). When \u003e0, overrides the per-type fitting recompute.",
                    "type": "number"
                },
                "liquidity_cap_pct": {
                    "description": "0..100, max share of daily volume per item",
                    "type": "number"
                },
                "max_item_pct": {
                    "description": "0..100, max share of capital per item",
                    "type": "number"
                },
                "region_id": {
                    "type": "integer"
                },
                "sec_zones": {
                    "description": "\"high\",\"low\",\"null\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ship_type_id": {
                    "type": "integer"
                },
                "time_budget_min": {
                    "description": "available trading minutes/day",
                    "type": "number"
                }
            }
        },
        "PortfolioResult": {
            "type": "object",
            "properties": {
                "diversification_score": {
                    "description": "0..100",
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/PortfolioItem"
                    }
                },
                "skills_applied": {
                    "$ref": "#/definitions/SkillsApplied"
                },
                "time_used_min": {
                    "type": "number"
                },
                "total_capital_used": {
                    "type": "number"
                },
                "total_daily_profit": {
                    "type": "number"
                }
            }
        },
        "RegionResponse": {
            "type": "object",
            "properties": {
                "region_id": {
                    "type": "integer",
                    "example": 10000002
                },
                "region_name": {
                    "type": "string",
                    "example": "The Forge"
                }
            }
        },
        "SkillsApplied": {
            "type": "object",
            "properties": {
                "accounting": {
                    "type": "integer",
                    "example": 5
                },
                "applied": {
                    "type": "boolean",
                    "example": true
                },
                "broker_fee_rate": {
                    "type": "number",
                    "example": 0.015
                },
                "broker_relations": {
                    "type": "integer",
                    "example": 5
                },
                "sales_tax_rate": {
                    "type": "number",
                    "example": 0.025
                }
            }
        },
        "TypeResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer",
                    "example": 4
                },
                "group_id": {
                    "type": "integer",
                    "example": 18
                },
                "packaged_volume": {
                    "type": "number",
                    "example": 0.01
                },
                "type_id": {
                    "type": "integer",
                    "example": 34
                },
                "type_name": {
                    "type": "string",
                    "example": "Tritanium"
                },
                "volume": {
                    "type": "number",
                    "example": 0.01
                }
            }
        },
        "VersionResponse": {
            "type": "object",
            "properties": {
                "build_time": {
                    "type": "string",
                    "example": "2025-11-12T10:00:00Z"
                },
                "git_commit": {
                    "type": "string",
                    "example": "abc123def"
                },
                "version": {
                    "type": "string",
                    "example": "0.1.0"
                }
            }
        },
        "models.AssetItem": {
            "type": "object",
            "properties": {
                "location_id": {
                    "type": "integer"
                },
                "location_name": {
                    "type": "string"
                },
                "marketable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "region_id": {
                    "type": "integer"
                },
                "system_id": {
                    "type": "integer"
                },
                "type_id": {
                    "type": "integer"
                }
            }
        },
        "models.AssetsResponse": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AssetItem"
                    }
                },
                "cache_expires_at": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "models.OreRankRow": {
            "type": "object",
            "properties": {
                "best": {
                    "type": "string"
                },
                "best_station_id": {
                    "type": "integer"
                },
                "best_station_name": {
                    "description": "Where to act:",
                    "type": "string"
                },
                "best_station_system": {
                    "description": "reprocess station system",
                    "type": "string"
                },
                "best_station_tax": {
                    "type": "number"
                },
                "crystal_multiplier": {
                    "description": "per ore; 1.0 = no crystals used",
                    "type": "number"
                },
                "cycle_minutes": {
                    "description": "fill + legs + stops",
                    "type": "number"
                },
                "delta_isk_per_hour": {
                    "type": "number"
                },
                "effective_isk_per_hour": {
                    "description": "Haul-downtime cycle (effective ISK/h, greedy one cycle from current system):",
                    "type": "number"
                },
                "estimate_reason": {
                    "description": "short reason, only when IsEstimate",
                    "type": "string"
                },
                "fill_minutes": {
                    "description": "time to fill the hold",
                    "type": "number"
                },
                "hull_yield_multiplier": {
                    "description": "Yield accuracy (hull role/skill bonus + best-case ore crystal):",
                    "type": "number"
                },
                "is_estimate": {
                    "description": "hull bonus / crystal not fully resolved",
                    "type": "boolean"
                },
                "load_volume_m3": {
                    "description": "ore-hold m³ filled per load",
                    "type": "number"
                },
                "market_loads": {
                    "description": "full ore-hold loads the Best path's best reachable order(s) can absorb (VolumeRemain cap); 0\u003cx\u003c1 means the best price won't even take one load",
                    "type": "number"
                },
                "materials": {
                    "description": "per-mineral sell breakdown",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RefineMaterial"
                    }
                },
                "mining_m3_per_hour": {
                    "type": "number"
                },
                "ore_name": {
                    "type": "string"
                },
                "ore_type_id": {
                    "type": "integer"
                },
                "raw_isk_per_hour": {
                    "type": "number"
                },
                "raw_net_per_m3": {
                    "type": "number"
                },
                "raw_sell": {
                    "description": "where to sell the raw ore",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SellLocation"
                        }
                    ]
                },
                "refine_isk_per_hour": {
                    "type": "number"
                },
                "refine_net_per_m3": {
                    "type": "number"
                },
                "route_jumps": {
                    "description": "jumps over the cycle's legs",
                    "type": "integer"
                },
                "sell_system_name": {
                    "description": "chosen sell hub (refine) / ore-sell system (raw)",
                    "type": "string"
                }
            }
        },
        "models.OreRankingRequest": {
            "type": "object",
            "properties": {
                "allow_low_sec": {
                    "description": "true = willing to operate in low-sec too",
                    "type": "boolean"
                },
                "region_id": {
                    "type": "integer"
                }
            }
        },
        "models.OreRankingResponse": {
            "type": "object",
            "properties": {
                "degraded_reason": {
                    "description": "human-readable explanation when any flag is set",
                    "type": "string"
                },
                "fitting_degraded": {
                    "description": "active-ship/modules fetch failed → m3h unreliable, NoMiningSetup not asserted",
                    "type": "boolean"
                },
                "no_mining_setup": {
                    "type": "boolean"
                },
                "not_available_reason": {
                    "description": "set when no ores apply here",
                    "type": "string"
                },
                "origin_station_name": {
                    "description": "docked station name, if any",
                    "type": "string"
                },
                "origin_system_id": {
                    "description": "character's current system (ranking origin)",
                    "type": "integer"
                },
                "origin_system_name": {
                    "description": "resolved name of the current system",
                    "type": "string"
                },
                "quarter": {
                    "description": "amarr|caldari|gallente|minmatar|\"\"",
                    "type": "string"
                },
                "region_id": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OreRankRow"
                    }
                },
                "skills_degraded": {
                    "description": "Degradation flags: true when the named ESI input could not be fetched\n(e.g. expired token) and a neutral fallback was used. The ranking is still\nreturned but the numbers are less accurate — the UI must surface this\ninstead of presenting degraded results as authoritative.",
                    "type": "boolean"
                },
                "standings_degraded": {
                    "type": "boolean"
                },
                "system_security": {
                    "description": "current system, displayed sec",
                    "type": "number"
                }
            }
        },
        "models.RefineMaterial": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number"
                },
                "effective_qty": {
                    "type": "integer"
                },
                "material_name": {
                    "type": "string"
                },
                "material_type_id": {
                    "type": "integer"
                },
                "sell": {
                    "$ref": "#/definitions/models.SellLocation"
                }
            }
        },
        "models.RouteCalculationRequest": {
            "type": "object",
            "properties": {
                "align_time": {
                    "description": "Optional: Deterministic align time in seconds (from fitting calculation)",
                    "type": "number",
                    "example": 4.8
                },
                "cargo_capacity": {
                    "description": "Optional: Override cargo capacity (m³)",
                    "type": "number",
                    "example": 62500
                },
                "include_volume_metrics": {
                    "description": "Optional: Whether to include volume metrics",
                    "type": "boolean",
                    "example": false
                },
                "max_liquidation_days": {
                    "description": "Optional: Maximum liquidation time (days)",
                    "type": "number",
                    "example": 7
                },
                "min_daily_volume": {
                    "description": "Optional: Minimum daily volume filter (items/day)",
                    "type": "number",
                    "example": 100
                },
                "region_id": {
                    "description": "Region ID (e.g., The Forge)",
                    "type": "integer",
                    "example": 10000002
                },
                "ship_type_id": {
                    "description": "Ship type ID (e.g., Bestower)",
                    "type": "integer",
                    "example": 649
                },
                "warp_speed": {
                    "description": "Optional: Deterministic warp speed in AU/s (from fitting calculation)",
                    "type": "number",
                    "example": 4.2
                }
            }
        },
        "models.RouteCalculationResponse": {
            "type": "object",
            "properties": {
                "calculation_time_ms": {
                    "type": "integer"
                },
                "cargo_capacity": {
                    "type": "number"
                },
                "region_id": {
                    "type": "integer"
                },
                "region_name": {
                    "type": "string"
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TradingRoute"
                    }
                },
                "ship_name": {
                    "type": "string"
                },
                "ship_type_id": {
                    "type": "integer"
                },
                "warning": {
                    "type": "string"
                }
            }
        },
        "models.SellLocation": {
            "type": "object",
            "properties": {
                "is_structure": {
                    "type": "boolean"
                },
                "location_id": {
                    "description": "station/structure id — in-game waypoint target",
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                },
                "system_name": {
                    "type": "string"
                }
            }
        },
        "models.SellOption": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number"
                },
                "has_data": {
                    "type": "boolean"
                },
                "isk_per_hour": {
                    "type": "number"
                },
                "jumps": {
                    "type": "integer"
                },
                "region_id": {
                    "type": "integer"
                },
                "region_name": {
                    "type": "string"
                },
                "scope": {
                    "description": "\"hub\" | \"current_region\"",
                    "type": "string"
                },
                "security_risk": {
                    "description": "\"safe\" | \"caution\" | \"danger\"",
                    "type": "string"
                },
                "station_id": {
                    "type": "integer"
                },
                "station_name": {
                    "type": "string"
                },
                "system_name": {
                    "type": "string"
                },
                "total_net": {
                    "type": "number"
                },
                "travel_time_min": {
                    "type": "number"
                },
                "unit_net": {
                    "type": "number"
                }
            }
        },
        "models.SellOptionsRequest": {
            "type": "object",
            "properties": {
                "avoid_low_sec": {
                    "type": "boolean"
                },
                "location_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "type_id": {
                    "type": "integer"
                }
            }
        },
        "models.SellOptionsResponse": {
            "type": "object",
            "properties": {
                "best": {
                    "$ref": "#/definitions/models.SellOption"
                },
                "name": {
                    "type": "string"
                },
                "not_routable_reason": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SellOption"
                    }
                },
                "origin_system_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "skills_applied": {
                    "$ref": "#/definitions/SkillsApplied"
                },
                "type_id": {
                    "type": "integer"
                }
            }
        },
        "models.TradingRoute": {
            "type": "object",
            "properties": {
                "base_cargo_capacity": {
                    "description": "Base capacity without skills",
                    "type": "number"
                },
                "base_isk_per_hour": {
                    "description": "ISK/h without navigation skills",
                    "type": "number"
                },
                "base_travel_time_seconds": {
                    "description": "Navigation Skills fields",
                    "type": "number"
                },
                "broker_fees": {
                    "description": "Combined broker fees (buy + sell)",
                    "type": "number"
                },
                "buy_broker_fee": {
                    "description": "Trading Fees fields (Issue #39)",
                    "type": "number"
                },
                "buy_price": {
                    "type": "number"
                },
                "buy_security_status": {
                    "type": "number"
                },
                "buy_station_id": {
                    "type": "integer"
                },
                "buy_station_name": {
                    "type": "string"
                },
                "buy_system_id": {
                    "type": "integer"
                },
                "buy_system_name": {
                    "type": "string"
                },
                "cargo_capacity": {
                    "description": "Total effective capacity (with skills + fitting)",
                    "type": "number"
                },
                "cargo_used": {
                    "description": "Cargo fields",
                    "type": "number"
                },
                "cargo_utilization": {
                    "description": "Percentage 0-100",
                    "type": "number"
                },
                "daily_profit": {
                    "description": "Profit per day (net_profit / liquidation_days)",
                    "type": "number"
                },
                "estimated_relist_fee": {
                    "description": "Estimated relist fee (sell broker fee)",
                    "type": "number"
                },
                "fitting_bonus_m3": {
                    "description": "Fitting modules bonus (absolute m³)",
                    "type": "number"
                },
                "gross_margin_percent": {
                    "description": "Gross profit margin %",
                    "type": "number"
                },
                "gross_profit": {
                    "description": "Profit before fees",
                    "type": "number"
                },
                "isk_per_hour": {
                    "type": "number"
                },
                "item_name": {
                    "type": "string"
                },
                "item_type_id": {
                    "type": "integer"
                },
                "item_volume": {
                    "type": "number"
                },
                "jumps": {
                    "type": "integer"
                },
                "liquidation_days": {
                    "description": "Estimated days to sell inventory",
                    "type": "number"
                },
                "min_route_security_status": {
                    "description": "Minimum security of all systems on route",
                    "type": "number"
                },
                "net_profit": {
                    "description": "Total profit minus all fees",
                    "type": "number"
                },
                "net_profit_percent": {
                    "description": "Net profit margin %",
                    "type": "number"
                },
                "number_of_tours": {
                    "description": "Multi-tour fields",
                    "type": "integer"
                },
                "profit_per_tour": {
                    "type": "number"
                },
                "profit_per_unit": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "round_trip_seconds": {
                    "type": "number"
                },
                "sales_tax": {
                    "description": "Sales tax on sell orders",
                    "type": "number"
                },
                "sell_broker_fee": {
                    "description": "Broker fee for sell order placement",
                    "type": "number"
                },
                "sell_price": {
                    "type": "number"
                },
                "sell_security_status": {
                    "type": "number"
                },
                "sell_station_id": {
                    "type": "integer"
                },
                "sell_station_name": {
                    "type": "string"
                },
                "sell_system_id": {
                    "type": "integer"
                },
                "sell_system_name": {
                    "type": "string"
                },
                "skill_bonus_percent": {
                    "description": "Total skill bonus %",
                    "type": "number"
                },
                "skilled_travel_time_seconds": {
                    "description": "Travel time with navigation skills applied",
                    "type": "number"
                },
                "spread_percent": {
                    "type": "number"
                },
                "time_improvement_percent": {
                    "description": "Percentage improvement from skills",
                    "type": "number"
                },
                "total_fees": {
                    "description": "Sum of all trading fees",
                    "type": "number"
                },
                "total_investment": {
                    "description": "Total ISK needed to purchase cargo (buy_price × quantity)",
                    "type": "number"
                },
                "total_profit": {
                    "type": "number"
                },
                "total_time_minutes": {
                    "type": "number"
                },
                "travel_time_seconds": {
                    "type": "number"
                },
                "volume_metrics": {
                    "description": "Volume \u0026 Liquidity fields (Issue #53)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.VolumeMetrics"
                        }
                    ]
                }
            }
        },
        "models.VolumeMetrics": {
            "type": "object",
            "properties": {
                "daily_isk_turnover": {
                    "description": "Average daily ISK traded (volume × avg_price)",
                    "type": "number"
                },
                "daily_volume_avg": {
                    "description": "30-day average daily volume",
                    "type": "number"
                },
                "data_days": {
                    "description": "Number of days of historical data available",
                    "type": "integer"
                },
                "liquidity_score": {
                    "description": "0-100 score based on volume stability",
                    "type": "integer"
                },
                "region_id": {
                    "type": "integer"
                },
                "type_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "EVE SSO Bearer Token. Format: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.34.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EVE-O-Provit API",
	Description:      "REST API for EVE Online trading, manufacturing and profit optimization\n\nFeatures:\n- Intra-region trading route calculation\n- Character skills and ship fitting integration\n- Deterministic cargo/warp speed calculations\n- Market data caching with staleness tracking\n- EVE SSO authentication",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
